version: '3'

tasks:
  generate_order_command:
    cmds:
      - |
       protoc -I proto \
        commands/create_order/order_service.proto \
        --go_out=./gen \
        --go_opt=paths=source_relative \
        --go-grpc_out=./gen \
        --go-grpc_opt=paths=source_relative

  generate_withdraw_command:
    cmds:
      - |
       protoc -I proto proto/commands/withdraw/winthdraw_service.proto \
        --go_out=./gen \
        --go_opt=paths=source_relative \
        --go-grpc_out=./gen \
        --go-grpc_opt=paths=source_relative

  generate_query_orders:
    cmds:
      - |
       protoc -I proto \
          queries/orders/query_orders.proto \
        --go_out=./gen \
        --go_opt=paths=source_relative \
        --go-grpc_out=./gen \
        --go-grpc_opt=paths=source_relative

  generate_query_accounting:
    cmds:
      - |
       protoc -I proto \
          queries/accounting/query_accounting.proto \
        --go_out=./gen \
        --go_opt=paths=source_relative \
        --go-grpc_out=./gen \
        --go-grpc_opt=paths=source_relative

  generate_transaction_processed_event:
    cmds:
      - |
       protoc -I proto \
        events/transaction_processed_event.proto \
        --go_out=./gen \
        --go_opt=paths=source_relative

  generate_order_events:
    cmds:
      - |
       protoc -I proto \
        events/order_events.proto \
        --go_out=./gen \
        --go_opt=paths=source_relative

  generate_accrual_events:
    cmds:
      - |
       protoc -I proto \
        events/accrual_events.proto \
        --go_out=./gen \
        --go_opt=paths=source_relative