version: '3'

tasks:
  generate_order_service:
    desc: "Generate order services code from proto files"  
    cmds:
      - protoc -I proto proto/order_service.proto --go_out=./gen/services/orders --go_opt=paths=source_relative --go-grpc_out=./gen/services/orders --go-grpc_opt=paths=source_relative
        

  generate_accounting_service:
    desc: "Generate accounting services code from proto files"  
    cmds:
      - protoc -I proto proto/accounting_service.proto --go_out=./gen/services/accounting --go_opt=paths=source_relative --go-grpc_out=./gen/services/accounting --go-grpc_opt=paths=source_relative

  generate_denormalized_order_service_service:
    desc: "Generate denormalized_order_servicecode from proto files"  
    cmds:
      - protoc -I proto proto/denormalized_order_service.proto --go_out=./gen/services/denormalized_order --go_opt=paths=source_relative --go-grpc_out=./gen/services/denormalized_order --go-grpc_opt=paths=source_relative
    
  generate_events:
    desc: "Generate events code from proto files"  
    cmds:
      - protoc -I proto proto/order_events.proto --go_out=./gen/events --go_opt=paths=source_relative

  generate_accrual_events:
    desc: "Generate Accrual events code from proto files"  
    cmds:
      - protoc -I proto proto/accrual_events.proto --go_out=./gen/events --go_opt=paths=source_relative


  generate_accounting_events:
    desc: "Generate accounting events code from proto files"  
    cmds:
      - protoc -I proto proto/accounting_events.proto --go_out=./gen/events --go_opt=paths=source_relative


  generate_order_events:
    desc: "Generate order events code from proto files"  
    cmds:
      - protoc -I proto proto/order_events.proto --go_out=./gen/events --go_opt=paths=source_relative